spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lwl
    username: dbuser
    password: user123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    
